name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: iOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - name: Create Payload folder
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app
        run: mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Create IPA
        run: zip -r Flowfade.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/Flowfade.ipa
          tag: beta
          overwrite: true
          body: "Flowfade beta build"
